config/routes.rb
Railsfootball::Application.routes.draw do
  resources :schools
  root 'static_pages#home'
  match '/cover', to: 'static_pages#cover', via: 'get'
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render action: 'show', status: :created, location: @school }
      else
        format.html { render action: 'new' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :conference, :body)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def cover
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
    <%= javascript_include_tag "application" %>
    <script type="text/javascript">
    var s = skrollr.init({
        forceHeight: false,
        smoothScrolling: false,
        mobileCheck: function() {
            return false;
        }
    });
    </script>

app/views/layouts/_header.html.erb
  <div class="fixed-custom">
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1><a href="#">SCTimes</a></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Left Nav Section -->
        <ul class="left">
          <li><%= link_to "High School Football", "#" %></li>
        </ul>
        <!-- Right Nav Section -->
        <ul class="right">
          <li><%= link_to "Cover Story", "#" %></li>
          <li class="has-dropdown">
            <a href="#">Teams & Conferences</a>
            <ul class="dropdown">
              <li class="has-dropdown">
                <a href="#">Central Lakes Conference</a>
                <ul class="dropdown">
                  <li><a href="">Rocori</a></li>
                  <li><a href="">St. Cloud Tech</a></li>
                  <li><a href="">St. Cloud Apollo</a></li>
                  <li><a href="">Sartell</a></li>
                  <li><a href="">Sauk Rapids</a></li>
                </ul>
              </li>
              <li class="has-dropdown">
                <a href="#">Granite Ridge Conference</a>
                <ul class="dropdown">
                  <li><a href="">St. Cloud Cathedral</a></li>
                  <li><a href="">Albany</a></li>
                  <li><a href="">Foley</a></li>
                  <li><a href="">Little Falls</a></li>
                  <li><a href="">Milaca</a></li>
                  <li><a href="">Becker</a></li>
                </ul>
              </li>
              <li class="has-dropdown">
                <a href="#">West Central Conference</a>
                <ul class="dropdown">
                  <li><a href="">Paynesville</a></li>
                  <li><a href="">Sauk Centre</a></li>
                  <li><a href="">Melrose</a></li>
                </ul>
              </li>
              <li class="has-dropdown">
                <a href="#">Central Minnesota Conference</a>
                <ul class="dropdown">
                  <li><a href="">Eden Valley-Watkins</a></li>
                  <li><a href="">Holdingford</a></li>
                  <li><a href="">Kimball</a></li>
                  <li><a href="">Pierz</a></li>
                </ul>
              </li>
              <li class="has-dropdown">
                <a href="#">Prairie South Conference</a>
                <ul class="dropdown">
                  <li><a href="">Royalton</a></li>
                  <li><a href="">Upsala/Swanville</a></li>
                </ul>
              </li>
              <li class="has-dropdown">
                <a href="#">Wright County Conference</a>
                <ul class="dropdown">
                  <li><a href="">Annandale</a></li>
                </ul>
              </li>
            </ul>
          </li>
        </ul>
      </section>
    </nav>
  </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= yield(:title) %> | High School Football '14</title>
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    "foundation_and_overrides" %>
    <%= stylesheet_link_tag    "custom" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <%= render 'layouts/header' %>

  <body>

    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :conference %><br>
    <%= f.text_field :conference %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Conference</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.conference %></td>
        <td><%= school.body %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Conference:</strong>
  <%= @school.conference %>
</p>

<p>
  <strong>Body:</strong>
  <%= @school.body %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>

app/views/static_pages/cover.html.erb
<% provide(:title, 'Cover Story title') %>
<div class="row" style="max-width:100%;  margin-top: 0px; padding-top:0px;">
	<section id="schooltesttop" class="slide">
	    <div class="bcg" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -100px;" data-anchor-target="#schooltesttop">
            <div class="hsContainer">
                <div class="hsContent" data-center="bottom: 200px; opacity: 1" data-top="bottom: 1200px; opacity: 0" data-anchor-target="#schooltesttop h3">
                	<h3>Story by: NAME | DATE</h3>
            		<h1 class="textwhite">Cover Story</h1>
	            </div>
	        </div>
	    </div>
	</section>
</div>
<div class="row">
	<div class="large-12 medium-12 columns">
		<h3>Headline here</h3>
		<p>Bacon ipsum dolor sit amet frankfurter short ribs sausage, bresaola drumstick jowl fatback tenderloin hamburger. Prosciutto spare ribs pork, pig shankle short ribs ground round shoulder beef ribs. Drumstick t-bone ribeye fatback bacon pork belly. Jowl corned beef andouille chicken, fatback ham hock hamburger bacon jerky biltong tail turkey. Filet mignon pork t-bone, chuck turducken kevin spare ribs pancetta landjaeger pork loin beef sausage pastrami bacon pork belly. Pork chop andouille bresaola bacon porchetta. Turducken beef tail brisket turkey ham jowl rump short loin short ribs shank tri-tip flank ball tip chuck.</p>

		<p>Beef ribs shoulder ham hock turducken flank shankle bacon pork chop doner tri-tip corned beef venison t-bone pork rump. Turducken leberkas porchetta ham. Kevin ham hock short ribs meatball jowl chuck shoulder, turkey corned beef spare ribs turducken. Sausage shankle frankfurter tenderloin. Sausage pork belly cow ball tip corned beef ground round prosciutto turducken. Pastrami landjaeger leberkas tri-tip, pork belly cow shank spare ribs jerky sausage.</p></p>

		<p>Pancetta short loin beef ribs jowl prosciutto ground round, biltong brisket filet mignon landjaeger kevin shank. Jowl shankle frankfurter, pig pork shank porchetta ham doner. Tongue flank ball tip andouille. Porchetta drumstick ribeye short loin ball tip pork. Ball tip sirloin bresaola pork tail salami, jowl shank drumstick ham hock short loin. Bacon pancetta cow ground round short loin ribeye.</p>

		<p>Sausage porchetta filet mignon turkey jowl salami andouille. Beef ribs meatloaf pork chop, t-bone tail tri-tip kevin drumstick ball tip pork loin leberkas. Porchetta shankle frankfurter strip steak meatball, leberkas beef ribs tongue fatback turkey corned beef kevin biltong. Pastrami bacon pancetta, prosciutto t-bone ham hock strip steak ham porchetta venison. Beef biltong sausage frankfurter t-bone tenderloin ham boudin turducken pastrami. Drumstick shankle bacon, landjaeger meatball kielbasa ribeye leberkas ham filet mignon. Beef ribs pastrami tri-tip, short loin jowl tenderloin landjaeger ground round swine.</p>

			<section id="ad1" class="slide">
			    <div class="bcg hide-for-small-only" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -100px;" data-anchor-target="#ad1">
			    </div>
			</section><br>

		<p>Tenderloin ham hock kevin andouille rump salami doner spare ribs shankle. Tri-tip pig doner kevin kielbasa tongue venison pancetta bresaola boudin jowl shankle andouille. Ground round kielbasa andouille meatloaf ham sirloin brisket venison beef shank beef ribs sausage ball tip cow short ribs. Hamburger corned beef shank, fatback chicken salami biltong sirloin t-bone pastrami leberkas drumstick ground round. Spare ribs landjaeger ribeye shank, flank chicken kevin turkey salami pork loin ground round tongue drumstick. T-bone pork belly kielbasa, tenderloin sirloin pork loin jowl swine. Boudin cow jowl filet mignon pork shankle ribeye meatloaf tenderloin frankfurter.</p>

		<p>Porchetta kevin kielbasa pancetta ball tip strip steak leberkas pastrami. Bacon kielbasa leberkas tongue prosciutto tri-tip pork belly capicola drumstick pork loin turkey. Short loin jowl chuck strip steak, meatball kevin t-bone. Short ribs pork chop sausage meatloaf brisket capicola ball tip bacon tenderloin t-bone chuck ham hock tail pork loin biltong. Pig kielbasa jowl tri-tip filet mignon rump.</p>

		<p>Brisket turducken tail swine kielbasa. Bacon spare ribs porchetta pastrami pork belly rump t-bone. Meatloaf kevin pancetta meatball kielbasa ribeye pork belly ball tip jowl chuck rump biltong flank. Meatloaf tongue meatball prosciutto jerky beef venison bacon cow flank ball tip ham hock pork loin porchetta. Pork loin pig pastrami, pancetta frankfurter chuck hamburger. Andouille filet mignon meatball shank kielbasa short ribs jowl strip steak.</p>

		<p>Brisket shank tenderloin, kevin turducken ribeye chuck strip steak tail pork chop pig boudin fatback. Chuck venison swine corned beef, ground round sirloin filet mignon tail ball tip shoulder pork chop cow. Pastrami pork loin tenderloin, salami meatloaf ball tip bacon porchetta pork. Turkey rump short loin bacon ball tip pork belly. Bresaola short loin pork, pancetta pastrami bacon cow corned beef swine kevin. Pork loin corned beef ham hock pork short ribs beef ribs jerky tenderloin tri-tip pig shank pork belly. Shankle doner short loin ground round pig pork belly chicken ham hock.</p>

		<p>Bacon chicken strip steak filet mignon landjaeger brisket beef pastrami meatball. Drumstick swine pancetta, venison spare ribs porchetta shankle frankfurter. Biltong chuck ham strip steak tongue filet mignon pork chop ribeye hamburger short ribs turkey doner. Short ribs andouille tail pig filet mignon bacon.</p>

		<p>Kevin salami shoulder frankfurter boudin swine drumstick brisket pork belly. Tenderloin pork chop kevin, ham tongue strip steak prosciutto meatball brisket. Corned beef ham hamburger pork chop cow fatback bresaola capicola pancetta drumstick meatball biltong landjaeger pig. Corned beef ham hock shoulder, capicola filet mignon spare ribs pork loin andouille. Turkey prosciutto filet mignon shankle, pastrami pork ham hock meatball bacon ham chuck. Jerky doner strip steak tenderloin bacon rump ribeye pork loin hamburger ground round leberkas chicken sirloin filet mignon.</p>		
	</div>
</div>
<div class="row">
    <p style="text-align:center"><a class="fancy radius button" href="http://www.sctimes.com/apps/pbcs.dll/gallery?Avis=DR&Dato=20130827&Kategori=GALLERIES01&Lopenr=308290038&Ref=PH" style="font-size:18px;margin-top:10px;">Click here for the gallery</a></p>
</div>
<div class="row" style="max-width:100%;  margin-top: 0px; padding-top:0px;">
	<section id="schooltestbot" class="slide">
	    <div class="bcg" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -100px;" data-anchor-target="#schooltestbot">
	    </div>
	</section>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
  <div class="row" style="max-width:100%; margin-top: 0px; padding-top:0px;" >
    <section id="cover" class="slide">
        <div class="bcg" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -100px;" data-anchor-target="#cover">
          <div class="hsContainer">
                <div class="hsContent" data-center="bottom: 200px; opacity: 1" data-top="bottom: 1200px; opacity: 0" data-anchor-target="#cover h3">
                <h1 class="textwhite">High School Football '14</h1>
              </div>
          </div>
        </div>
    </section>
  </div>
  <div class="row shadow">
    <div class="large-12 columns">
      <h1>BIG TITLE</h1>
    </div>
  </div>

  <div class="row shadow">
    <div class="large-12 medium-12 columns">
      <h5>See what’s ahead this season for 21 Central Minnesota high school football teams.</h5>
      <div class="row">
        <div class="large-4 medium-4 columns">
          <div class="callout panel">
            <h5>Central Lakes Conference</h5>
            <ul>
              <li><i class="fa fa-graduation-cap"></i><a href="">Rocori</a></li>
              <li><a href="">St. Cloud Tech</a></li>
              <li><a href="">St. Cloud Apollo</a></li>
              <li><a href="">Sartell</a></li>
              <li><a href="">Sauk Rapids</a></li>
            </ul>
          </div>
        </div>
        <div class="large-4 medium-4 columns">
          <div class="callout panel">
            <h5>Granite Ridge Conference</h5>
            <ul>
              <li><a href="">St. Cloud Cathedral</a></li>
              <li><a href="">Albany</a></li>
              <li><a href="">Foley</a></li>
              <li><a href="">Little Falls</a></li>
              <li><a href="">Milaca</a></li>
              <li><a href="">Becker</a></li>
            </ul>
          </div>
        </div>
        <div class="large-4 medium-4 columns">
          <div class="callout panel">
            <h5>West Central Conference</h5>
            <ul>
              <li><a href="">Paynesville</a></li>
              <li><a href="">Sauk Centre</a></li>
              <li><a href="">Melrose</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="large-4 medium-4 columns">
          <div class="callout panel">
            <h5>Central Minnesota Conference</h5>
            <ul>
              <li><a href="">Sth</a></li>
              <li><a href="">Sth</a></li>
              <li><a href="">Sth</a></li>
              <li><a href="">Sth</a></li>
            </ul>
          </div>
        </div>
        <div class="large-4 medium-4 columns">
          <div class="callout panel">
            <h5>Prairie South Conference</h5>
            <ul>
              <li><a href="">Sth</a></li>
              <li><a href="">Sth</a></li>
              <li><a href="">Sth</a></li>
              <li><a href="">Sth</a></li>
            </ul>
          </div>
        </div>
        <div class="large-4 medium-4 columns">
          <div class="callout panel">
            <h5>Wright County Conference</h5>
            <ul>
              <li><a href="">Sth</a></li>
              <li><a href="">Sth</a></li>
              <li><a href="">Sth</a></li>
              <li><a href="">Sth</a></li>
            </ul>
          </div>
        </div>
    </div>
    <hr />
</div>